# Generated by Django 6.0.5 on 2026-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
