# Generated by Django 6.0.5 on 2026-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['full_name'],
            },
        ),
    ]
