# Generated by Django 6.0.5 on 2026-05-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank', 'Bank Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_reference', models.CharField(blank=True, max_length=50)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
